// Generated by CoffeeScript 1.4.0
var app, express, pkg, stitch;

stitch = require("stitch");

express = require("express");

app = express();

app.set("view engine", "ejs");

app.use(express["static"](__dirname + '/public'));

app.get("/", function(req, res) {
  return res.render("index");
});

pkg = stitch.createPackage({
  paths: ["" + __dirname + "/src"]
});

app.get("/bundle.js", pkg.createServer());

app.listen(9000);

console.log("Server running at http://localhost:9000");
