// Generated by CoffeeScript 1.4.0
var Board, Game;

Board = require("./board");

module.exports = Game = (function() {

  function Game(canvas) {
    var _this = this;
    this.board = new Board;
    this.canvas = canvas;
    this.ctx = this.canvas.getContext("2d");
    console.log("Game initialized");
    this.canvas.onclick = function(evt) {
      _this.board.infectNeighbors(_this.board.positionToHex(evt.offsetX, evt.offsetY));
      return _this.draw();
    };
  }

  Game.prototype.draw = function() {
    this.ctx.setTransform(1, 0, 0, 1, 0, 0);
    this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    return this.board.draw(this.ctx);
  };

  return Game;

})();
