// Generated by CoffeeScript 1.4.0
var Board, Hex;

Board = require("./board");

module.exports = Hex = (function() {

  Hex.NUM_STATES = 5;

  Hex.STATE_TO_COLOR = ["#FFFFFF", "#FF9999", "#99FF99", "#FFFF99", "#9999FF"];

  function Hex(coordinate, position) {
    this.coordinate = coordinate;
    this.position = position;
    this.state = 0;
  }

  Hex.prototype.getColor = function() {
    return Hex.STATE_TO_COLOR[this.state];
  };

  Hex.prototype.setState = function(x) {
    return this.state = x % Hex.NUM_STATES;
  };

  return Hex;

})();
